#+title: Gentmaint

* Description
- Package:      GentMaint
- Description:  bash scripts to aid the maintenance of a Gentoo Linux system
- Homepage:     https://gentmaint.sourceforge.net
- Copyright:    (c) 2008-2024, AstroFloyd - astrofloyd.org
- Licence:      [[https://www.eupl.eu/1.2/en/][EUPL 1.2]]

GentMaint is a collection of simple bash scripts to aid the maintenance of a 
Gentoo Linux system. You should give them a good look before actually using 
them, and you're strongly discouraged from using them as cron jobs, even though 
that's what I designed (some of) them for ;-). They can be used under the 
conditions of version 1.2 of the EUPL.  To download the GentMaint package, read the 
code documentation, or to contact the developer, see: 
https://gentmaint.sourceforge.net/


* Installation

Copy the scripts into a directory in your path, e.g. ~/usr/local/sbin/~ They should be executed with root
permissions.

Run  ~gentmaint-help~  for a short description of each script.


* Licence

Copyright 2008-2024 AstroFloyd - astrofloyd.org

This file is part of the GentMaint package.

This is free software: you can redistribute it and/or modify it under the terms of the European Union Public
Licence, either version 1.2 of the Licence, or (at your option) any later version.

This software is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the
implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the European Union Public
Licence for more details.

You should have received a copy of the European Union Public Licence along with this code (LICENCE).  If not,
see https://www.eupl.eu/1.2/en/.




