#!/bin/bash

## GentMaint: tools for Gentoo maintenance
## Copyright (c) AstroFloyd, 2008-2015, gentmaint.sf.net
##
## gentmaint-sync-cron: run gentmaint-sync as cron job


# Run gentmaint-sync:
gentmaint-sync &> /dev/null

