#!/bin/bash

## GentMaint: tools for Gentoo maintenance
## Copyright (c) AstroFloyd, 2008-2021, gentmaint.sf.net
##
## gentmaint-help: list the available scripts


# Print package/version banner:
gentmaint-version header


cat <<EOF

    Available scripts:
  
    gentmaint-check-deps:                  Check the dependencies of an installed package
    gentmaint-clean:                       Clean the Gentoo system
    gentmaint-consistent:                  Check the Gentoo system for consistency, and uninstall
                                             obsolete dependencies
    gentmaint-help:                        Produce this list
    gentmaint-lastlog:                     Display the log of the last World update
    gentmaint-log:                         Run dispatch-conf and list recent updates
    gentmaint-mark-revdep-rebuild-done:    In the specified GentMaint log file(s), add "  --  Done" to
                                             the end of lines matching "revdep-rebuild --library", so
                                             that they will no longer be displayed by gentmaint-log.
    gentmaint-sync:                        Sync the Gentoo portage system
    gentmaint-sync-cron:                   Run gentmaint-sync as a cron job
    gentmaint-update:                      Sync and update the Gentoo system.  This script expects no
                                             interactive user feedback by default.  Use emerge option
                                             -a to change that, or -p to pretend.
    gentmaint-update-cron:                 Run gentmaint-update as a cron job.  You should be *very*
                                             careful when doing this and spend some time
                                             investigating the logs afterwards
    gentmaint-version:                     Print package/version info
    gentmaint-worldupdate1:                Update the Gentoo World system in an interactive shell, but don't sync
    gentmaint-worldupdate2:                As gentmaint-worldupdate1, but including changed use flags and build-time dependencies
    gentmaint-worldupdate3:                As gentmaint-worldupdate1, but deep
    gentmaint-worldupdate4:                As gentmaint-worldupdate2+3
    					     Updating the system in stages (1-4) decreases the probability of blocks

EOF

