#!/bin/bash

## GentMaint: tools for Gentoo maintenance
## Copyright (c) AstroFloyd, 2008-2018, gentmaint.sf.net
##
## gentmaint-sync: sync the Gentoo portage system


# Print package/version banner:
gentmaint-version header


# Sync Layman:
echo -e "\n\n\n\n\n\E[1mGentMaint: syncing layman\E[0m"
time nice -19 layman -S


# Sync Portage:
echo -e "\n\n\n\n\n\E[1mGentMaint: syncing portage\E[0m"
#time nice -19 emerge -q --sync
time nice -19 eix-sync -q


# Regenerate metadata caches for faster dependency calculations:
#   (takes ~20min - first time only? - ~30s second time in a row)
echo -e "\n\n\n\n\n\E[1mGentMaint: regenerating metadata caches\E[0m"
time nice -19 emerge -q --regen
if [ ${?} != 0 ]
then
    echo -e "\n  GentMaint: regenerating metadata caches failed, aborting...\n" 1>&2
    exit 1
fi




# Download distfiles:
echo -e "\n\n\n\n\n\E[1mGentMaint: downloading world packages\E[0m"
time nice -19 emerge -uvf --deep --newuse world ${@}
if [ ${?} != 0 ]
then
    echo -e "\n  GentMaint: updating world failed, aborting...\n" 1>&2
    exit 1
fi


# Run dispatch-conf:
echo -e "\n\n\n\n\n\E[1mGentMaint: running dispatch-conf\E[0m"
dispatch-conf


# Finish:
echo -e "\n\n\n"
date
echo -e "\n\n\n\E[1mGentMaint: done\E[0m"
echo -e "\n\n\n"

