#!/bin/bash

## GentMaint: tools for Gentoo maintenance
## Copyright (c) AstroFloyd, 2008-2014, gentmaint.sf.net
##
## gentmaint-sync: sync the Gentoo portage system


# Print package/version banner:
gentmaint-version header


# Sync Layman:
echo -e "\n\n\n\n\n\E[1mSyncing layman\E[0m"
time nice -19 layman -S


# Sync Portage:
echo -e "\n\n\n\n\n\E[1mSyncing portage\E[0m"
#time nice -19 emerge -q --sync
time nice -19 eix-sync -q


# Download distfiles:
echo -e "\n\n\n\n\n\E[1mDownloading world packages\E[0m"
time nice -19 emerge -uvf --deep --newuse world ${@}
if [ ${?} != 0 ]
then
    echo -e "\n  Updating world failed, aborting...\n" 1>&2
    exit 1
fi


# Run dispatch-conf:
echo -e "\n\n\n\n\n\E[1mRunning dispatch-conf\E[0m"
dispatch-conf


# Finish:
echo -e "\n\n\n"
date
echo -e "\n\n\n\E[1mDone\E[0m"
echo -e "\n\n\n"

