#!/bin/bash

## GentMaint: tools for Gentoo maintenance
## Copyright (c) AstroFloyd, 2008-2023, gentmaint.sf.net
##
## gentmaint-clean: clean the Gentoo system


# Print package/version banner:
gentmaint-version header


# Remove old distfiles and packages:
echo -e "\n\n\n\n\n\E[1mGentMaint: removing old distribution files and packages\E[0m"
echo "Running eclean -d distfiles..."
nice -19 eclean -d distfiles

echo "Running eclean -d packages..."
nice -19 eclean -d packages


# Compress log files:
echo -e "\n\n\E[1mGentMaint: compressing /var/log/portage/*.log...\E[0m"
echo -n "Initial size: "
du --max-depth=0 -h /var/log/portage/  | awk '{print $1}'
nice -19 bzip2 -q9 /var/log/portage/*.log
echo -n "Final size:   "
du --max-depth=0 -h /var/log/portage/  | awk '{print $1}'

echo -e "\n\n\E[1mGentMaint: compressing /var/log/gentmaint/...\E[0m"
echo -n "Initial size: "
du --max-depth=0 -h /var/log/gentmaint/  | awk '{print $1}'
nice -19 gzip -q9 /var/log/gentmaint/auto/*.log
nice -19 bzip2 -q9 /var/log/gentmaint/manual/*.log
echo -n "Final size:   "
du --max-depth=0 -h /var/log/gentmaint/  | awk '{print $1}'


# Clean portage build directories:
echo -e "\n\n\E[1mGentMaint: cleaning portage build directories (/var/tmp/portage/*)...\E[0m"
rm -rf /var/tmp/portage/*


# Finish:
echo -e "\n\n\n"
date
echo -e "\n\n\n\E[1mGentMaint: done\E[0m"
echo -e "\n\n\n"

