#!/bin/bash

## GentMaint: tools for Gentoo maintenance
## Copyright (c) AstroFloyd, 2008-2024, gentmaint.sf.net
## Inspired by xarthisius, 2011-12-07
##
## gentmaint-check-configure-options: check the configuration options of an unpacked package


# Print package/version banner:
gentmaint-version header

# Check arguments:
if [ ${#} -ne 1 ]
then
    echo -e "\n  gentmaint-check-configure-options:  Check the autotools configure options of an unpacked package"
    echo -e "                                        syntax:  gentmaint-check-configure-options: </path/to/configure>\n"
    
    # exit 1
    
    CAT_PKG=`pwd | sed 's|.*/\([^/]*/[^/]*\)$|\1|'`
    echo "  No package provided, assuming you're in the ebuild directory and using $CAT_PKG as the package name."
else
    CAT_PKG="$1"
fi

PKG=`echo $CAT_PKG | sed 's|^.*/||'`


# List configure options:
echo
echo "  Configure options found:"
/var/tmp/portage/portage/${CAT_PKG}-*/work/${PKG}-*/configure --help  \
    | grep -E -A1 --color=always '\-\-enable|\-\-disable' \
    | grep -vE '\-option-checking|\-FEATURE|\-dependency-tracking|\-silent-rules|\-osx-version-check|build shared libraries|do not reject slow dependency extractors|speeds up one-time build' \
    | sed 's|.*|  &|'
echo


echo
echo -e "  \E[1;45mIUSE\E[0m variable for the ebuild:"
echo -n '    IUSE="'
# Turn configure options into a list of USE flags:
#  * --enable-static[default=yes] is changed to --enable-static-libs[default=no]
#  * --enabled is removed
#  * --disabled is replaced by -
#  * [default=yes] is replaced by +
#  * [default=no] is replaced by -
#  * -- is replaced by +
#  * -+ is replaced by -
#  * leading - is removed (since -flag == flag in IUSE)
#  * any remaining [...] (e.g. [=PKGS]) is removed
#  * everything starting from the first space is removed
/var/tmp/portage/portage/${CAT_PKG}-*/work/${PKG}-*/configure --help  \
    | grep -E '\-\-enable|\-\-disable' \
    | grep -vE '\-option-checking|\-FEATURE|\-dependency-tracking|\-silent-rules|\-osx-version-check|build shared libraries' \
    | sed -e 's|--enable-static\[=PKGS\]  build static libraries \[default=yes\]|--enable-static-libs\[=PKGS\]  build static libraries \[default=no\]|g' \
	  -e 's|^ *--enable-||' -e 's|^ *--disable-|-|' \
    | sort \
    | sed -e 's|^\(.*\) \(\[default=no\]\)|-\1|' -e 's|^\(.*\) \(\[default=yes\]\)|+\1|' -e 's|^--|\+|' -e 's|^-\+|-|' \
	  -e 's|\[.*\]| |g' -e 's| .*$||' \
    | sed -z -e 's|\n| |g' -e 's| *$||' -e 's|^-||' -e 's| -| |g'
echo '"'
echo


# Econf command for the ebuild:
echo
echo -e "  \E[1;45mEconf\E[0m command for the ebuild:"
echo "src_configure() {"
echo "    econf \\"
/var/tmp/portage/portage/${CAT_PKG}-*/work/${PKG}-*/configure --help  \
    | grep -E '\-\-enable|\-\-disable' \
    | grep -vE '\-option-checking|\-FEATURE|\-dependency-tracking|\-silent-rules|\-osx-version-check|build shared libraries' \
    | sed -e 's|--enable-||' -e 's|--disable-||' -e "s|^ *\([^ ]*\)\(.*$\)|        \$(use_enable \1) \\\\|" \
	  -e 's|\[.*\]||g' -e 's|\$(use_enable static)|\$(use_enable static-libs static)|g' \
    | sort \
    | sed -z 's| \\\n$||g'
echo
echo "}"
echo


# Create a list of USE flags for metadata.xml:
echo
echo -e "  List of USE flags and descriptions for \E[1;45mmetadata.xml\E[0m:"
echo "  <use>"
/var/tmp/portage/portage/${CAT_PKG}-*/work/${PKG}-*/configure --help  \
    | grep -E '\-\-enable|\-\-disable' \
    | grep -vE '\-option-checking|\-FEATURE|\-dependency-tracking|\-silent-rules|\-osx-version-check|build shared libraries' \
    | sed -e 's|--enable-||' -e 's|--disable-||' -e "s|^ *\([^ ]*\) *\([^ ]\)|    <flag name='\1'>\U\2\E|" \
	  -e 's|$|</flag>|' -e 's| \[default=.*\]||' -e "s|'>\]</flag>|\]'></flag>|" -e 's| *\[.*\]||g' \
    | grep -v "<flag name='static'>" \
    | sort
echo "  </use>"


echo
