#!/bin/bash

## GentMaint: tools for Gentoo maintenance
## Copyright (c) AstroFloyd, 2008-2024, gentmaint.sf.net
## Inspired by xarthisius, 2011-12-07
##
## gentmaint-check-deps: check the dependencies of an installed package


# Print package/version banner:
gentmaint-version header

# Check arguments:
if [ ${#} -ne 1 ]
then
    echo -e "\n  gentmaint-check-deps:  Check the dependencies of an installed package"
    echo -e "                           syntax:  gentmaint-check-deps <package name>\n"
    
    # exit 1
    
    PKG=`pwd | sed 's|.*/\([^/]*/[^/]*\)$|\1|'`
    echo "  No package provided, assuming you're in the ebuild directory and using $PKG as the package name."
else
    PKG="$1"
fi

# List dependencies:
#  1) qlist: list files owned by package
#  2) scanelf: list linked libraries per file
#  3) tr: replace commas with spaces
#  4) qfile: list packages that own these files
#  5) sort: sort
#  6) sed: remove name of linked package file, add indentation for RDEPEND in ebuild,
#  7) uniq: filter out duplicates,
#  8) grep: remove self and gcc, glibc
echo -e "\n  GentMaint: scanning for dependencies of $PKG:"
qlist "$PKG" \
    | xargs scanelf -L -n -q -F '%n #F' \
    | tr , ' ' \
    | xargs qfile -C \
    | sort -u \
    | sed -e 's/^\([^:]*\): .*$/         \1/g' \
    | uniq \
    | grep -vE "${PKG}|sys-devel/gcc|sys-libs/glibc"
echo

