#!/bin/bash

## GentMaint: tools for Gentoo maintenance
## Copyright (c) AstroFloyd, 2008-2023, gentmaint.sf.net
##
## gentmaint-consistent: check the Gentoo system for consistency, 
##                       and clean obsolete dependencies


# Print package/version banner:
gentmaint-version header


# Run emerge @preserved-rebuild:
echo -e "\n\n\n\n\n\E[1mGentMaint: running emerge @preserved-rebuild\E[0m"
time nice -19 emerge -v @preserved-rebuild ${@}


# Run depclean:
echo -e "\n\n\n\n\n\E[1mGentMaint: running emerge --depclean\E[0m"
time nice -19 emerge -t --depclean ${@}


# Run revdep-rebuild:
echo -e "\n\n\n\n\n\E[1mGentMaint: running revdep-rebuild\E[0m"
time nice -19 revdep-rebuild -- -vt ${@}


# Clean Portage:
gentmaint-clean


# Run dispatch-conf:
echo -e "\n\n\n\n\n\E[1mGentMaint: running dispatch-conf\E[0m"
dispatch-conf


# Finish:
echo -e "\n\n\n"
date
echo -e "\n\n\n\E[1mGentMaint: done\E[0m"
echo -e "\n\n\n"

