#!/bin/bash

## GentMaint: tools for Gentoo maintenance
## Copyright (c) AstroFloyd, 2008-2024, gentmaint.sf.net
##
## gentmaint-worldupdate: Update the Gentoo world system in an interactive shell, but don't sync


# Print package/version banner:
gentmaint-version header


# Mount boot partition:
mount /boot/


# Update world 1/4:
echo -e "\n\n\n\n\n\E[1mGentMaint: running emerge world update\E[0m"
time nice -19 emerge --update -v --with-bdeps=n --backtrack=30 --keep-going world ${@}


# Unmount boot partition:
umount /boot/


# Run dispatch-conf:
echo -e "\n\n\n\n\n\E[1mGentMaint: running dispatch-conf\E[0m"
dispatch-conf


# Finish:
echo -e "\n\n\n"
date
echo -e "\n\n\n\E[1mGentMaint: done\E[0m"
echo -e "\n\n\n"

