#!/bin/bash

## GentMaint: tools for Gentoo maintenance
## Copyright (c) AstroFloyd, 2008-2015, gentmaint.sf.net
##
## gentmaint-lastlog: display the log of the last world update


# Print package/version banner:
gentmaint-version header


echo -e "\n\n\E[1mGentMaint: displaying log of the last world update...\E[0m"
lastlog=`ls /var/log/gentmaint/auto/gentmaint-update__* |tail -n1`
echo -e "Log file: "${lastlog}
less ${lastlog}
echo -e "\n\E[1mGentMaint: done\E[0m"

