#!/bin/bash

## GentMaint: tools for Gentoo maintenance
## Copyright (c) AstroFloyd, 2008-2024, gentmaint.sf.net
##
## gentmaint-update-cron: run gentmaint-update as cron job
##                        you should be very careful when doing this and spend some time
##                        investigating the logs afterwards


# Get date for log-file name:
if [ `date +%H` -ge 21 ]; then
    # Starting close to midnight; use tomorrow's date:
    date=$(date +%Y-%m-%d -d tomorrow)
else
    date=$(date +%Y-%m-%d)
fi

# Name of the log file contains date and one of a-z to allow multiple instances:
for ver in {a..z}; do
	logname=$(date +/var/log/gentmaint/auto/gentmaint-update__$date$ver.log)
	# echo $logname
	
	# Use this name if it (or its zipped cousin) does not yet exist:
	if [[ ! -e $logname && ! -e $logname.gz ]]; then
		break
	fi
done


# Run gentmaint-update:
gentmaint-update &> ${logname}


# Compress the log file:
nice -19 gzip -9 ${logname} &> /dev/null

