#!/bin/bash

## GentMaint: tools for Gentoo maintenance
## Copyright (c) AstroFloyd, 2008-2015, gentmaint.sf.net
##
## gentmaint-consistent: check the Gentoo system for consistency, 
##                       and clean obsolete dependencies


# Print package/version banner:
gentmaint-version header


# Run emerge @preserved-rebuild:
echo -e "\n\n\n\n\n\E[1mRunning emerge @preserved-rebuild\E[0m"
time nice -19 emerge -v @preserved-rebuild ${@}


# Use eix to find packages that can be [U]pgraded, [D]owngraded or whose status is unknown [?]:
echo -e "\n\n\n\n\n\E[1mUpdating packages found by eix:\E[0m"
emerge -vu1 ${@} `eix | grep '^\[[UD?]\]' | awk '{print $2}'`


# Run depclean:
echo -e "\n\n\n\n\n\E[1mRunning emerge --depclean\E[0m"
time nice -19 emerge -t --depclean ${@}


# Run revdep-rebuild:
echo -e "\n\n\n\n\n\E[1mRunning revdep-rebuild\E[0m"
time nice -19 revdep-rebuild -- -vt ${@}


# Clean Portage:
gentmaint-clean


# Run dispatch-conf:
echo -e "\n\n\n\n\n\E[1mRunning dispatch-conf\E[0m"
dispatch-conf


# Use eix to find packages that should STILL can be [U]pgraded, [D]owngraded or whose status is unknown [?]:
echo -e "\n\n\n\n\n\E[1mPackages found by eix that should be checked manually:\E[0m"
eix | grep '^\[[UD?]\]'


# Finish:
echo -e "\n\n\n"
date
echo -e "\n\n\n\E[1mDone\E[0m"
echo -e "\n\n\n"

