#!/bin/bash

## GentMaint: tools for Gentoo maintenance
## Copyright (c) AstroFloyd, 2008-2015, gentmaint.sf.net
##
## gentmaint-log: run dispatch-conf and list recent updates


# Print package/version banner:
gentmaint-version header


# Show the last 3 log files by default:
n=${1}

if [ ${#} -eq 0 ]
then
    n=3
fi


# Run dispatch-conf:
echo -e '\nRunning dispatch-conf...'
dispatch-conf
echo -e 'Done.\n'



# Check automated update log files:
cd /var/log/gentmaint/auto

pwd
echo "Last ${n} updates:"
for file in `ls gentmaint-update__* |tail -n ${n}`
do
    echo -e "Processing \E[1;32m${file}\E[0m"
    if [ `echo ${file} | grep -E '\.gz$'` ]
    then
	zgrep 'Emerging ' ${file}  &&  echo
	zgrep revdep-rebuild ${file} | grep library | grep -vi done  &&  echo
	zgrep -H 'failed, aborting' ${file}  |  sed 's/.*/\x1B[1;31m&\x1B[0m/'
    else
	bzgrep 'Emerging ' ${file}  &&  echo
	bzgrep revdep-rebuild ${file} | grep library | grep -vi done  &&  echo
	bzgrep -H 'failed, aborting' ${file}  |  sed 's/.*/\x1B[1;31m&\x1B[0m/'
    fi
    echo
done

cd - &> /dev/null



# Check manual-update log files:
cd /var/log/gentmaint/manual

echo
zgrep revdep-rebuild `ls 20??-??-??__*.log* |tail -n ${n}` |grep library | grep -vi done

echo
zgrep -H 'failed, aborting' `ls 20??-??-??__*.log* |tail -n 1`

echo

cd - &> /dev/null

echo -e ''

